### PR TITLE
WIP: A DSL for situation

### PR DESCRIPTION
**Pull request by bsunderhus**
Ok, here we go!
The has been a while since the #4 so, without delays, a DSL is required!
@pereirazc I'll add here some usefull info for us to tackle this subject, articles and stuff that I intent to follow.

like this guys ideas of what are the [features of a situation](https://pextra.slack.com/files/isaac/F319TS32B/pervasive_and_mobile_computing.pdf).

### CODE REVIEW

**Comment by bsunderhus** [comment]
Ok, so first of all. We're talking here about an external DSL or an internal one?.

External means that it is independant of other languages and therefore we must create our own syntax and parser for it as well.

Internal, obviously is the oposite. Is a DSL that depends upon another languages therefore is bounded by it's restrictions, buuuuut we wouldn't need much about the syntax and the parser, since the language is almost ready.

**Comment by pereirazc** [comment]
It may not be a DSL, could be an exchange representation of a common model for CEP at first. Similar to `XChangeEQ`.

**Comment by bsunderhus** [comment]
Ok, after some analysis, the [XchangeEQ](https://pdfs.semanticscholar.org/3d06/3fa0bc9a07b0c7b2f240eac3fa3fb2436476.pdf) is more of two things than just one. It exposes a mean to present `events` in XML diverse formats (he gives as example SOAP or Common Base Event format) and a query language, that would be the `XChangeEQ` itself (EQ = Event Query).

What you're proposing is a `Domain Specific Query Language` for us to make sense out of situations detections and **only** detections, there would be no way of situation declaration or anything like that in this language. So my main question is, how would it be this declaration?

**Comment by pereirazc** [comment]
@BernardoS actually every `query` is a `declaration` for an event or situation, let me show how I imagine a situation declaration inspired by the **XChangeEQ**:

```
DETECT Fever FOR {febrile: x}
ON {
  x: Person(temperature > 37)
}
END
```
going nuts on this one:
```
DETECT Murder FOR {murderer: x, murdered: y}
ON {
  x: Person(alive)
  y: Person(!alive, killedby x)
}
END
```

**Comment by bsunderhus** [comment]
@pereirazc I see. So basically we attain to declare a situation by it's occurrence.

It'd be nice to see a more complex example with this annotation in practice, [fraud scenario](https://github.com/pextralabs/fraud-scenario) perhaps.

But still, I'm having some doubts of how will we fit this together with the current model in the scene using drools. I can see the query part working easily, like the `when` statement in drools, but the XML stuff.... not so clear to me.

**Comment by pereirazc** [comment]
I dreamed a dream... 😔

**Pull request closed without merging**
